import type { ReferenceDoc } from '../../types/fichas.js'

/**
 * Documentos oficiais em que as fichas de primeiros socorros se baseiam. O
 * servidor baixa cada um da fonte oficial quando tem internet, confere o sha256
 * e guarda em storage/referencias, para a consulta funcionar offline. Os PDFs
 * não ficam no repositório.
 */
export const REFERENCE_DOCS: ReferenceDoc[] = [
  {
    id: 'ms-fiocruz-primeiros-socorros-2003',
    title: 'Manual de Primeiros Socorros',
    publisher: 'Ministério da Saúde / Fundação Oswaldo Cruz (FIOCRUZ)',
    year: 2003,
    url: 'https://bvsms.saude.gov.br/bvs/publicacoes/manual_primeiros_socorros.pdf',
    sha256: '4f110686a10c4e1ecf847397f40340d2df92ad106262729ce524a903bb3d76f2',
    sizeBytes: 9549199,
    license: 'É permitida a reprodução parcial ou total desta obra, desde que citada a fonte.',
    audience: 'public',
    topic: 'health',
  },
  {
    id: 'ms-samu-suporte-basico-de-vida-2016',
    title: 'Protocolos de Suporte Básico de Vida — SAMU 192',
    publisher: 'Ministério da Saúde',
    year: 2016,
    url: 'https://bvsms.saude.gov.br/bvs/publicacoes/protocolo_suporte_basico_vida.pdf',
    sha256: 'f39edb612b1713ce9027ec58818146342265353ed3aecd8166c2a8c97f90d058',
    sizeBytes: 16541991,
    license:
      'Sem autorização de reprodução explícita; os protocolos dizem que "adaptações são permitidas de acordo com as particularidades dos serviços". As fichas usam texto próprio e citam a fonte.',
    audience: 'professional',
    topic: 'health',
  },
  {
    id: 'ms-cartilha-queimaduras-2012',
    title: 'Cartilha para tratamento de emergência das queimaduras',
    publisher: 'Ministério da Saúde',
    year: 2012,
    url: 'https://bvsms.saude.gov.br/bvs/publicacoes/cartilha_tratamento_emergencia_queimaduras.pdf',
    sha256: '4b69e98c9886a39dbfd9139db4403f95b10da35313c20034c0aced350bc79a92',
    sizeBytes: 2598199,
    license:
      'É permitida a reprodução parcial ou total desta obra, desde que citada a fonte e que não seja para venda ou qualquer fim comercial.',
    audience: 'public',
    topic: 'health',
  },
  {
    id: 'ms-guia-animais-peconhentos-2024',
    title: 'Guia de Animais Peçonhentos do Brasil',
    publisher: 'Ministério da Saúde',
    year: 2024,
    url: 'https://bvsms.saude.gov.br/bvs/publicacoes/guia_animais_peconhentos_brasil.pdf',
    sha256: '83537defa5aa608377970014ac280584b329a328cd12eeed3b04ce07c4dee861',
    sizeBytes: 19959925,
    license:
      'Creative Commons Atribuição–NãoComercial–CompartilhaIgual 4.0. É permitida a reprodução parcial ou total desta obra, desde que citada a fonte.',
    audience: 'public',
    topic: 'health',
  },
  {
    id: 'ms-caderneta-crianca-2024',
    title: 'Caderneta da Criança — Passaporte da Cidadania (7ª edição)',
    publisher: 'Ministério da Saúde',
    year: 2024,
    url: 'https://bvsms.saude.gov.br/bvs/publicacoes/caderneta_crianca_menino_passaporte_cidadania_7ed.pdf',
    sha256: '012aee4bb49de04e47238841c651c92927916ff6608b1b365ef8ec3ee44ccfe6',
    sizeBytes: 14656857,
    license:
      'Creative Commons Atribuição–NãoComercial–CompartilhaIgual 4.0. É permitida a reprodução parcial ou total desta obra, desde que citada a fonte.',
    audience: 'public',
    topic: 'health',
  },
  {
    id: 'ms-manejo-diarreia-cartaz',
    title: 'Manejo do Paciente com Diarreia (cartaz)',
    publisher: 'Ministério da Saúde',
    year: 2014,
    url: 'https://bvsms.saude.gov.br/bvs/cartazes/manejo_paciente_diarreia_cartaz.pdf',
    sha256: 'b19a1f0ec04cec2b8ae280008af0b6d5bf93a35e42ce36cd11af2cccafbc9526',
    sizeBytes: 216456,
    license: 'Sem nota de licença no documento. As fichas usam texto próprio e citam a fonte.',
    audience: 'public',
    topic: 'health',
  },
  {
    id: 'ms-orientacoes-enchentes',
    title: 'Orientações à População em Situação de Enchentes',
    publisher: 'Ministério da Saúde',
    year: 2024,
    url: 'https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/enchentes/orientacoes-a-populacao-em-situacao-de-enchentes.pdf',
    sha256: '93441d26f426c97db6776569015c1b2f137b2ef817d63b0cb6c4c0cbea15f24e',
    sizeBytes: 533260,
    license: 'Sem nota de licença no documento. As fichas usam texto próprio e citam a fonte.',
    audience: 'public',
    topic: 'health',
  },
  // --- Comunicação por rádio (guias) ---
  {
    id: 'anatel-cartilha-radioamador-2026',
    title: 'Cartilha do Serviço Radioamador (versão 2026-06)',
    publisher: 'Anatel',
    year: 2026,
    url: 'https://sistemas.anatel.gov.br/anexar-api/publico/anexos/download/e2bee3ec4783c5c41a8ce4affe7baef8',
    sha256: 'ebfb6b2404b8b579507434ce143d94b1ef4e2a5a290694867d089e5c41a379d6',
    sizeBytes: 1517183,
    license: 'Material público de orientação da Anatel. Os guias usam texto próprio e citam a fonte.',
    audience: 'public',
    topic: 'radio',
  },
  {
    id: 'anatel-ato-14448-2017',
    title: 'Ato nº 14.448/2017 — requisitos técnicos dos equipamentos de radiação restrita (item 15: rádio de uso geral)',
    publisher: 'Anatel',
    year: 2017,
    format: 'html',
    url: 'https://informacoes.anatel.gov.br/legislacao/atos-de-certificacao-de-produtos/2017/1139-ato-14448',
    sha256: '',
    sizeBytes: 0,
    mustContain: ['15.1.3. A potência efetivamente radiada', '462,5625'],
    license: 'Ato normativo: sem proteção de direito autoral (Lei 9.610/1998, art. 8º, IV).',
    audience: 'public',
    topic: 'radio',
  },
  {
    id: 'anatel-resolucao-680-2017',
    title: 'Resolução nº 680/2017 — Regulamento sobre Equipamentos de Radiocomunicação de Radiação Restrita',
    publisher: 'Anatel',
    year: 2017,
    format: 'html',
    url: 'https://informacoes.anatel.gov.br/legislacao/resolucoes/2017/936-resolucao-680',
    sha256: '',
    sizeBytes: 0,
    mustContain: ['não têm direito à proteção contra interferências prejudiciais'],
    license: 'Ato normativo: sem proteção de direito autoral (Lei 9.610/1998, art. 8º, IV).',
    audience: 'public',
    topic: 'radio',
  },
  {
    id: 'lei-9472-1997',
    title: 'Lei nº 9.472/1997 — Lei Geral de Telecomunicações',
    publisher: 'Presidência da República',
    year: 1997,
    format: 'html',
    url: 'https://www.planalto.gov.br/ccivil_03/leis/l9472.htm',
    sha256: '',
    sizeBytes: 0,
    mustContain: ['Independerão de outorga'],
    license: 'Lei: sem proteção de direito autoral (Lei 9.610/1998, art. 8º, IV).',
    audience: 'public',
    topic: 'radio',
  },
  {
    id: 'anatel-ato-3445-2026',
    title: 'Ato nº 3.445/2026 — requisitos operacionais do Serviço Rádio do Cidadão',
    publisher: 'Anatel',
    year: 2026,
    format: 'html',
    url: 'https://informacoes.anatel.gov.br/legislacao/atos-de-requisitos-operacionais-de-outorga-e-licenciamento/2149-ato-3445',
    sha256: '',
    sizeBytes: 0,
    mustContain: ['verificará se o canal está livre', 'composto do prefixo PX'],
    license: 'Ato normativo: sem proteção de direito autoral (Lei 9.610/1998, art. 8º, IV).',
    audience: 'public',
    topic: 'radio',
  },
  {
    id: 'anatel-resolucao-777-2025',
    title: 'Resolução nº 777/2025 — Regulamento Geral dos Serviços de Telecomunicações (RGST)',
    publisher: 'Anatel',
    year: 2025,
    format: 'html',
    url: 'https://informacoes.anatel.gov.br/legislacao/resolucoes/2025/2022-resolucao-777',
    sha256: '',
    sizeBytes: 0,
    mustContain: ['somente poderão explorar o Serviço de Rádio do Cidadão'],
    license: 'Ato normativo: sem proteção de direito autoral (Lei 9.610/1998, art. 8º, IV).',
    audience: 'public',
    topic: 'radio',
  },
  {
    id: 'anatel-resolucao-789-2026',
    title: 'Resolução nº 789/2026 — Plano de Atribuição, Destinação e Distribuição de Faixas de Frequências (PDFF)',
    publisher: 'Anatel',
    year: 2026,
    format: 'html',
    url: 'https://informacoes.anatel.gov.br/legislacao/resolucoes/2026/2157-resolucao-789',
    sha256: '',
    sizeBytes: 0,
    mustContain: ['RÁDIO DO CIDADÃO', '26960-27500'],
    license: 'Ato normativo: sem proteção de direito autoral (Lei 9.610/1998, art. 8º, IV).',
    audience: 'public',
    topic: 'radio',
  },
  {
    id: 'anatel-resolucao-444-2006-revogada',
    title: 'Resolução nº 444/2006 — antiga canalização do Rádio do Cidadão (REVOGADA)',
    publisher: 'Anatel',
    year: 2006,
    format: 'html',
    url: 'https://informacoes.anatel.gov.br/legislacao/resolucoes/2006/325-resolucao-444',
    sha256: '',
    sizeBytes: 0,
    mustContain: ['O canal 9 é restrito ao tráfego de mensagens referentes a situações de emergência'],
    license: 'Ato normativo: sem proteção de direito autoral (Lei 9.610/1998, art. 8º, IV). Guardada só como referência histórica.',
    audience: 'public',
    topic: 'radio',
  },
  {
    id: 'govbr-servico-radio-do-cidadao',
    title: 'Obter o Serviço Rádio do Cidadão (Carta de Serviços)',
    publisher: 'Governo Federal (gov.br)',
    year: 2026,
    format: 'html',
    url: 'https://www.gov.br/pt-br/servicos/obter-servico-radio-do-cidadao',
    sha256: '',
    sizeBytes: 0,
    mustContain: ['Prata ou Ouro'],
    license: 'Página informativa do governo federal. Os guias usam texto próprio e citam a fonte.',
    audience: 'public',
    topic: 'radio',
  },
]
