/**
 * Remédios: a base offline é a das bulas americanas (FDA), em inglês. Quem
 * procura "paracetamol" precisa achar "acetaminophen".
 *
 * Os motivos em FORA_DOS_EUA estão em inglês porque são chaves de tradução.
 */

/** Nome do princípio ativo no Brasil → nome nas bulas americanas. Sem acento e em minúsculas. */
export const NOMES_NAS_BULAS: Record<string, string> = {
  'paracetamol': 'acetaminophen',
  'acido acetilsalicilico': 'aspirin',
  'aas': 'aspirin',
  'aspirina': 'aspirin',
  'ibuprofeno': 'ibuprofen',
  'naproxeno': 'naproxen',
  'diclofenaco': 'diclofenac',
  'cetoprofeno': 'ketoprofen',
  'loratadina': 'loratadine',
  'desloratadina': 'desloratadine',
  'cetirizina': 'cetirizine',
  'levocetirizina': 'levocetirizine',
  'fexofenadina': 'fexofenadine',
  'clorfeniramina': 'chlorpheniramine',
  'dexclorfeniramina': 'dexchlorpheniramine',
  'difenidramina': 'diphenhydramine',
  'prometazina': 'promethazine',
  'dimenidrinato': 'dimenhydrinate',
  'meclizina': 'meclizine',
  'omeprazol': 'omeprazole',
  'pantoprazol': 'pantoprazole',
  'esomeprazol': 'esomeprazole',
  'lansoprazol': 'lansoprazole',
  'famotidina': 'famotidine',
  'ranitidina': 'ranitidine',
  'hidroxido de magnesio': 'magnesium hydroxide',
  'hidroxido de aluminio': 'aluminum hydroxide',
  'carbonato de calcio': 'calcium carbonate',
  'bicarbonato de sodio': 'sodium bicarbonate',
  'simeticona': 'simethicone',
  'loperamida': 'loperamide',
  'bisacodil': 'bisacodyl',
  'subsalicilato de bismuto': 'bismuth subsalicylate',
  'macrogol': 'polyethylene glycol',
  'polietilenoglicol': 'polyethylene glycol',
  'docusato': 'docusate',
  'sene': 'sennosides',
  'senosideos': 'sennosides',
  'guaifenesina': 'guaifenesin',
  'dextrometorfano': 'dextromethorphan',
  'fenilefrina': 'phenylephrine',
  'pseudoefedrina': 'pseudoephedrine',
  'oximetazolina': 'oxymetazoline',
  'nafazolina': 'naphazoline',
  'cloreto de sodio': 'sodium chloride',
  'hidrocortisona': 'hydrocortisone',
  'clotrimazol': 'clotrimazole',
  'miconazol': 'miconazole',
  'cetoconazol': 'ketoconazole',
  'terbinafina': 'terbinafine',
  'tolnaftato': 'tolnaftate',
  'fluconazol': 'fluconazole',
  'nistatina': 'nystatin',
  'neomicina': 'neomycin',
  'bacitracina': 'bacitracin',
  'polimixina b': 'polymyxin b',
  'lidocaina': 'lidocaine',
  'benzocaina': 'benzocaine',
  'oxido de zinco': 'zinc oxide',
  'calamina': 'calamine',
  'permetrina': 'permethrin',
  'pirantel': 'pyrantel',
  'albendazol': 'albendazole',
  'mebendazol': 'mebendazole',
  'ivermectina': 'ivermectin',
  'melatonina': 'melatonin',
  'doxilamina': 'doxylamine',
  'nicotina': 'nicotine',
  'carvao ativado': 'activated charcoal',
  'amoxicilina': 'amoxicillin',
  'azitromicina': 'azithromycin',
  'cefalexina': 'cephalexin',
  'ciprofloxacino': 'ciprofloxacin',
  'metronidazol': 'metronidazole',
  'sulfametoxazol': 'sulfamethoxazole',
  'doxiciclina': 'doxycycline',
  'prednisona': 'prednisone',
  'prednisolona': 'prednisolone',
  'dexametasona': 'dexamethasone',
  'salbutamol': 'albuterol',
  'adrenalina': 'epinephrine',
  'epinefrina': 'epinephrine',
  'losartana': 'losartan',
  'captopril': 'captopril',
  'enalapril': 'enalapril',
  'anlodipino': 'amlodipine',
  'hidroclorotiazida': 'hydrochlorothiazide',
  'furosemida': 'furosemide',
  'metformina': 'metformin',
  'glibenclamida': 'glyburide',
  'sinvastatina': 'simvastatin',
  'atorvastatina': 'atorvastatin',
  'levotiroxina': 'levothyroxine',
  'varfarina': 'warfarin',
  'clopidogrel': 'clopidogrel',
  'sertralina': 'sertraline',
  'fluoxetina': 'fluoxetine',
  'amitriptilina': 'amitriptyline',
  'escopolamina': 'scopolamine',
  'metoclopramida': 'metoclopramide',
  'ondansetrona': 'ondansetron',
}

/**
 * Nomes que existem no Brasil mas não nas bulas americanas: em vez de "nada
 * encontrado", a tela explica e sugere o parecido.
 */
export const FORA_DOS_EUA: Record<string, { motivo: string; parecido?: string }> = {
  'dipirona': { motivo: 'Dipyrone is not sold in the United States, so it has no FDA label.', parecido: 'paracetamol' },
  'metamizol': { motivo: 'Dipyrone is not sold in the United States, so it has no FDA label.', parecido: 'paracetamol' },
  'nimesulida': { motivo: 'Nimesulide is not sold in the United States, so it has no FDA label.', parecido: 'ibuprofeno' },
  'butilescopolamina': { motivo: 'Hyoscine butylbromide is not sold in the United States, so it has no FDA label.' },
  'buscopan': { motivo: 'Hyoscine butylbromide is not sold in the United States, so it has no FDA label.' },
}

/**
 * Como as pessoas chamam alguns remédios → nome da monografia no Formulário
 * Terapêutico Nacional (sem acento). Inclui marcas muito conhecidas.
 */
export const APELIDOS_NO_FTN: Record<string, string> = {
  'aas': 'acido acetilsalicilico',
  'aspirina': 'acido acetilsalicilico',
  'soro caseiro': 'sais para reidratacao oral',
  'soro de reidratacao': 'sais para reidratacao oral',
  'soro de reidratacao oral': 'sais para reidratacao oral',
  'sro': 'sais para reidratacao oral',
  'soro fisiologico': 'cloreto de sodio',
  'adrenalina': 'epinefrina',
  'novalgina': 'dipirona',
  'metamizol': 'dipirona',
  'tylenol': 'paracetamol',
  'bactrim': 'sulfametoxazol + trimetoprima',
  'amoxil': 'amoxicilina',
  'aerolin': 'salbutamol',
  'rivotril': 'clonazepam',
  'puran': 'levotiroxina',
}
